/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_panoeye_pano_JNIServerLib */

#ifndef _Included_com_panoeye_pano_JNIServerLib
#define _Included_com_panoeye_pano_JNIServerLib
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
